[db]
database_dsn = "postgresql+asyncpg://postgres:password@db/test"

[logging]
path = "logs/log_{time}.log"

[api]
title = "qwerty123"

[security]
secret_key = "blabla"

[redis]
dsn = "redis://secret@redis/1"
