[db]
database_dsn = "postgresql+asyncpg://postgres:password@db/test"

[logging]
path = "logs/log_{time}.log"

[api]
title = "qwerty123"

[security]
secret_key = "blabla"

[redis]
dsn = "redis://password@redis/1"

[mailing]
sender_password = "password"
sender_email = "gmail@gmail.com"
