[db]
database_dsn = "postgresql+asyncpg://postgres:password@localhost:5432/karma_system"

[logging]
path = "logs/log_{time}.log"

[api]
title = "qwerty123"

[security]
secret_key = "blabla"

[redis]
dsn = "redis://password@localhost:6379/1"
