version: '3.8'
services:
    db:
        image: postgres:14-alpine
        restart: "unless-stopped"
        environment:
            POSTGRES_USER: ${DB__USER}
            PG_PASSWORD: ${DB__PASSWORD}
            POSTGRES_DB: ${DB__NAME}
            VOLUMES_DIR: ${VOLUMES_DIR}
        volumes:
            - "${VOLUMES_DIR}/pg-data:/var/lib/postgresql/data"
        ports:
            - "15432:5432"
    db_migration:
        build:
            context: ..
            dockerfile: ./Dockerfile
        restart: "on-failure"
        depends_on:
            - db
        env_file: .env
        command: ["/wait-for-it/wait-for-it.sh", "db:5432", "-t", "2", "--", "python", "-m", "alembic", "upgrade", "head"]
    api:
        build:
            context: ..
        stop_signal: SIGINT
        restart: "unless-stopped"
        env_file: .env
        depends_on:
            - db
            - db_migration
            - redis
        ports:
            - "8000:80"
    redis:
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - "${VOLUMES_DIR}/redis-data:/data/"
            - "./redis.conf:/usr/local/etc/redis/redis.conf"
        environment:
            - REDIS_PASSWORD=${REDIS__PASSWORD}
            - REDIS_PORT=6379
            - REDIS_DATABASES=16