"""add files models

Revision ID: 1db96ce81df8
Revises: 3fba3b9e225e
Create Date: 2023-12-23 00:03:21.100475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.base.database.types


# revision identifiers, used by Alembic.
revision: str = '1db96ce81df8'
down_revision: Union[str, None] = '3fba3b9e225e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('file_id', app.base.database.types.GUID(), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('file_id', name=op.f('pk_documents')),
    sa.UniqueConstraint('file_url', name=op.f('uq_documents_file_url'))
    )
    op.create_index(op.f('ix_documents_file_id'), 'documents', ['file_id'], unique=True)
    op.create_table('photos',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('file_id', app.base.database.types.GUID(), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('file_id', name=op.f('pk_photos')),
    sa.UniqueConstraint('file_url', name=op.f('uq_photos_file_url'))
    )
    op.create_index(op.f('ix_photos_file_id'), 'photos', ['file_id'], unique=True)
    op.create_table('videos',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('file_id', app.base.database.types.GUID(), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('file_id', name=op.f('pk_videos')),
    sa.UniqueConstraint('file_url', name=op.f('uq_videos_file_url'))
    )
    op.create_index(op.f('ix_videos_file_id'), 'videos', ['file_id'], unique=True)
    op.alter_column('games', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('games', 'description',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.create_index(op.f('ix_games_name'), 'games', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_name'), table_name='games')
    op.alter_column('games', 'description',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('games', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_index(op.f('ix_videos_file_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_photos_file_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_documents_file_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
