"""add session db

Revision ID: 3fba3b9e225e
Revises: 7a4c0c5f01f1
Create Date: 2023-12-15 14:18:50.867015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fba3b9e225e'
down_revision: Union[str, None] = '7a4c0c5f01f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_session',
    sa.Column('session_id', sa.String(length=256), nullable=False),
    sa.Column('id', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_user_session'))
    )
    op.create_index(op.f('ix_user_session_session_id'), 'user_session', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_session_session_id'), table_name='user_session')
    op.drop_table('user_session')
    # ### end Alembic commands ###
