"""Add online column

Revision ID: 40306176ebaf
Revises: 8e78c3498f65
Create Date: 2023-12-11 16:05:47.705201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40306176ebaf'
down_revision: Union[str, None] = '8e78c3498f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('online', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'online')
    # ### end Alembic commands ###
