"""Add icon_id

Revision ID: 4e1d3c32f2ee
Revises: 9d080c04397e
Create Date: 2023-12-27 23:15:16.008058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.base.database.types


# revision identifiers, used by Alembic.
revision: str = '4e1d3c32f2ee'
down_revision: Union[str, None] = '9d080c04397e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('icon_id', app.base.database.types.GUID(), nullable=True))
    op.create_foreign_key(op.f('fk_servers_icon_id_photos'), 'servers', 'photos', ['icon_id'], ['file_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_servers_icon_id_photos'), 'servers', type_='foreignkey')
    op.drop_column('servers', 'icon_id')
    # ### end Alembic commands ###
