"""Add links to models

Revision ID: 7da9d5a294bc
Revises: 1db96ce81df8
Create Date: 2023-12-25 15:17:59.820014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da9d5a294bc'
down_revision: Union[str, None] = '1db96ce81df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('discord_link', sa.String(length=4096), nullable=True))
    op.add_column('servers', sa.Column('website_link', sa.String(length=4096), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'website_link')
    op.drop_column('servers', 'discord_link')
    # ### end Alembic commands ###
