"""add photo id

Revision ID: 9d080c04397e
Revises: 7da9d5a294bc
Create Date: 2023-12-25 21:50:02.716548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.base.database.types


# revision identifiers, used by Alembic.
revision: str = '9d080c04397e'
down_revision: Union[str, None] = '7da9d5a294bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_id', app.base.database.types.GUID(), nullable=True))
    op.create_foreign_key(op.f('fk_users_photo_id_photos'), 'users', 'photos', ['photo_id'], ['file_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_photo_id_photos'), 'users', type_='foreignkey')
    op.drop_column('users', 'photo_id')
    # ### end Alembic commands ###
